### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#1]
It would be good if we had an instant search for the help. Currently not possible using gh-pages. Proposals at stackoverflow: http://stackoverflow.com/a/28553417/873282

**Comment by Siedlerchr** [comment]
I will try around with this idea:
https://github.com/christian-fei/Simple-Jekyll-Search

**Comment by koppor** [comment]
Reading the above stackoverflow article and inspecting https://github.com/slashdotdash/jekyll-lunr-js-search closer, I came to following feature wishes:

 - full text search
 - display preview of results

This is not achieved by any plugins, so I played around with Google Custom Search available at <https://github.com/JabRef/help.jabref.org/tree/add_google_custom_search>.

Here an example:

![grabbed_20160916-163558](https://cloud.githubusercontent.com/assets/1366654/18589633/e61962e0-7c2b-11e6-86aa-658ca8d55e4b.png)

Issues

 - [ ] Search glass not aligned with box
 - [ ] Box resizes after anything is input
 - [ ] Table borders in search results (refs #72)

Currently, too much effort for me.

**Comment by tobiasdiez** [comment]
Could we nonetheless merge the current version? It looks a bit unfinished but is better than no search at all. And maybe somebody else fixes the last issues.

**Comment by Siedlerchr** [comment]
What about the SimpleSearch I posted above?
Example: http://christianfei.com/Simple-Jekyll-Search/

**Comment by koppor** [comment]
https://github.com/christian-fei/Simple-Jekyll-Search does full-text-search, but no **preview of the results**.

Further, we estimate that at the search page, ~3MB of (uncompressed) JSON is transferred to the user. This is not that mobile friendly, but could be OK for the desktop user.

**Comment by Siedlerchr** [comment]
Ah okay. I think we can style the Google Custom search:
http://digitaldrummerj.me/blogging-on-github-part-7-adding-a-custom-google-search/

There is already stylesheet code

**Comment by koppor** [comment]
I did a straight-forward integration by scoping our markdown styling hacks (adding `jabrefcontent` as precondition). Good enough now. Feel free to play around with CSS :innocent:
