### ISSUE TITLE
ScienceDirect: help file should not be listed in index

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#103]
Currently, ScienceDirect is not part of the web fetchers anymore, but may be sometimes (see https://github.com/JabRef/jabref/issues/1258). Hence, the help file (https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/ScienceDirect.md) was kept out of the index (http://help.jabref.org/en/).

Following the introduction of the automatization script, the help file is now listed in the index.

**Comment by Siedlerchr** [comment]
When I understand the automation script correctly, simply removing it from the en dir would be enough.
And then re-running the script.  (I can't test it atm here)

**Comment by mlep** [comment]
Is there a way of not removing it? Like just renaming it. So that when the ScienceDirect fetcher is back, it can be activated easily.

**Comment by Siedlerchr** [comment]
Hm I think renaming the extension to .old or whatever should work

Am 12.10.2016 6:44 nachm. schrieb "MLEP" <notifications@github.com>:
