### ISSUE TITLE
Define the status of each help page, and set priorities for update

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#11]
Some help pages are really out of date.

I suggest to:
1) label them by indicating at the top of the page if the content is deprecated, up-to-date, etc.
2) set priorities for updating the pages
3) inform translators when a new page is considered up-to-date, and so worth translating

I could work on it. But before I start, if you have any suggestions, they are very welcome!

**Comment by simonharrer** [comment]
A good idea.

We should communicate this through the jabref mailing list - maybe we get people on the train which are willing to help. 

Maybe it is worth of stating something like since which JabRef Version a specific feature described in the help file is available. 

We should add a "last changed date" for each help page, which also indicates whether it is old or not.

**Comment by mlep** [comment]
To make editing by users easier (and so have a larger community of contributors), I suggest to transfer the help pages to a wiki. How difficult would it be?

**Comment by stefan-kolb** [comment]
I would already be happy if we had a good english documentation...so translating help files is more of a nice to have.

**Comment by mlep** [comment]
@stefan-kolb Sure. If we do not have a good English help, there is nothing to be translated (moreover, based on the survey, translation was a low priority).
Just in case: **Translation challenge! #1128** is about the translation of the UI only.

**Comment by oscargus** [comment]
It it possible to automatically include e.g. code in the pages? For example, I provided an updated custom import format, but it is a bit of a hassle to replace it for each language...

(PR still open by the way... https://github.com/JabRef/custom-imports/pull/1 I don't have the right bits...)

**Comment by mlep** [comment]
@orscargus Is your comment related to this issue? Maybe you wrote your comment to the wrong place?

**Comment by oscargus** [comment]
Not directly maybe, but at least related to the help pages. Maybe it is
only the custom import format that is affected but I've thinking about this
issue, including a file in a help page, for a while... It could for example
also help in automatically updating the translation status by building the
table part everytime something is merged.

**Comment by Siedlerchr** [comment]
@oscargus  Seems to be possible:
http://awestruct.org/auto-deploy-to-github-pages/
Or here:
https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example
Or here they discuss the problem, too:
http://stackoverflow.com/questions/15214762/how-can-i-sync-documentation-with-github-pages

**Comment by mlep** [comment]
Woah! Great! I did not even imagine that was possible!

**Comment by koppor** [comment]
@oscargus: Could you open a separate issue to ease tracking?

**Comment by koppor** [comment]
@mlep Our current solution is close to a Wiki. Just click on "Edit" this page. If a user doesn't have a GitHub account, the pen icon is disabled:

![grabbed_20160408-082239](https://cloud.githubusercontent.com/assets/1366654/14375656/27baf47c-fd63-11e5-833d-aa7199a00070.png)

The fly over help clearly says that one has to log in. Once logged in, GitHub really supports the user in editing and to offer a pull request. With that way, we can review the contributions similar to code contributions.

**Comment by koppor** [comment]
@Siedlerchr Thank you for the link. For refrence: https://github.com/X1011/git-directory-deploy is the solution when publishing a subfolder only. At [TSDBCompare](https://github.com/TSDBBench/TSDBCompare), I did it with an encrypted SSH key. Have to investigate, which way works better.

**Comment by mlep** [comment]
Thanks @koppor for the description. Indeed, it is close to a wiki.
I was thinking of an editing process even closer to wikipedia because:
- I fell we do not need to review the changes before publication for the help (as long as we can undo them).
- creating a github account maybe a barrier in attracting new contributions.
- most users are not programmers, but maybe more used to free wikipedia (anonymous-contribution) process.

**Comment by mlep** [comment]
How shall we proceed to improve our help?

**Comment by Siedlerchr** [comment]
I would first suggest getting an overview which help page actually is referenced in the JabRef Code.
Then we can further review the list to see which are outdated.

**Comment by mlep** [comment]
Can this be done by somebody which is not versed in Java nor in JabRef code organization? (like myself) If yes, how?

**Comment by simonharrer** [comment]
Have a look at the HelpFiles.java class. It should show a lot of files which are used - but they are not complete as each fetcher has its own help file, plus the one for open office. I think we should create an enum to ensure that we know all available help files which are references from JabRef.

**Comment by Siedlerchr** [comment]
@simonharrer  I'll take a loot at this.

**Comment by mlep** [comment]
Here a first diagnosis. What's next?

Help file name			| In HelpFiles.java 
----------------------------	| ------------------------
ACMPortalHelp.md		| [ ]
Autosave.md			| [x]
BaseFrameHelp.md		| [ ]
BibtexHelp.md			| [ ]
CiteSeerHelp.md			| [ ]
CommandLine.md			| [ ]
ContentSelectorHelp.md		| [ ]
cpl-v10.md			| [ ]
CustomEntriesHelp.md		| [ ]
CustomExports.md		| [x]
CustomImports.md		| [x]
DatabaseProperties.md		| [ ]
DiVAtoBibTeXHelp.md		| [ ]
DOAJHelp.md			| [ ]
DOItoBibTeXHelp.md		| [ ]
EndNoteFilters.md		| [ ]
EntryEditorHelp.md		| [ ]
ExternalFiles.md		| [ ]
FileLinks.md			| [ ]
GeneralFields.md		| [x]
GoogleScholarHelp.md		| [ ]
GroupsHelp.md			| [ ]
GVKHelp.md			| [ ]
HelpHelp.md			| [ ]
IEEEXploreHelp.md		| [ ]
ImportInspectionDialog.md	| [x]
index.md			| []
ISBNtoBibTeXHelp.md		| [ ]
JabRefHelp.md			| [ ]
JournalAbbreviations.md		| [x]
JSTOR.md			| [ ]
LabelPatterns.md		| [x]
MarkingHelp.md			| [ ]
MedlineHelp.md			| [x]
OpenOfficeIntegration.md	| [ ]
OwnerHelp.md			| [x]
PreviewHelp.md			| [x]
RemoteHelp.md			| [x]
RevisionHistory.md		| [ ]
ScienceDirect.md		| [ ]
SearchHelp.md			| for regular expressions only
SpecialFieldsHelp.md		| [x]
Spires.md			| [ ]
SpringerHelp.md			| [ ]
SQLExport.md			| [ ]
StringEditorHelp.md		| [ ]
StringsHelp.md			| [ ]
TimeStampHelp.md		| [x]
XMPHelp.md			| [ ]

**Comment by Siedlerchr** [comment]
I think you missed a few: (the name of the help pages are in "") in my commit: (Maybe you took the left side as basis?)  You have to look at the "green" changes on the right.
I added all the fetchers to the Help Files
ACM, Google Scholar , DOI2Bibtex DOAJ, , Content Selector, Groups, IEEXPlore and some other are inlcuded already.

**Comment by mlep** [comment]
Indeed, on my screen, only the red part is displayed... I got it now! Thanks

**Comment by mlep** [comment]
Done (I believe...)

**Comment by Siedlerchr** [comment]
Okay, looks good! 
From what I know, JSTOR can be deleted.
Spires got renamed to INSPIRE (I did that rename some time ago in the help files)
All fetchers should have an own page.

**Comment by simonharrer** [comment]
The ones that are not references should get a button in the UI to make the help more explicit to the user.

**Comment by mlep** [comment]
I have just corrected it for INSPIRE.
Missing fetcher pages = ADS, Bibsonomy, DBLP, OAI2_ARXIV. I will create pages (that will have to be populated later).
And HelpHelp.md should be removed (#6).

**Comment by mlep** [comment]
**Status update:**

----------------------------
Existing help files		| HelpFiles.java 
----------------------------	| ------------------------
ACMPortalHelp.md		| [x]
ADSHelp.md			| [x]
Autosave.md			| [x]
BaseFrameHelp.md		| [ ]
**no file**				| Empty argument for FETCHER_BIBSONOMY_SCRAPE
BibtexHelp.md			| [ ]
CiteSeerHelp.md		| [x]
CommandLine.md		| Empty argument for COMMAND_LINE
ContentSelectorHelp.md	| [x]
cpl-v10.md			| [ ]
CustomEntriesHelp.md	| [ ]
CustomExports.md		| [x]
CustomImports.md		| [x]
DatabaseProperties.md	| [ ]
DiVAtoBibTeXHelp.md	| [x]
DBLPHelp.md			| [x]
DOAJHelp.md			| [x]
DOItoBibTeXHelp.md	| [x]
EndNoteFilters.md		| [ ]
EntryEditorHelp.md		| [x]
ExternalFiles.md		| [x]
FileLinks.md			| [ ]
GeneralFields.md		| [x]
GoogleScholarHelp.md	| [x]
GroupsHelp.md		| [x]
GVKHelp.md			| [x]
HelpHelp.md			| [ ]
IEEEXploreHelp.md		| [x]
ImportInspectionDialog.md	| [x]
index.md				| Empty argument for CONTENTS
ISBNtoBibTeXHelp.md	| [x]
JabRefHelp.md		| [ ]
JournalAbbreviations.md	| [x]
JSTOR.md			| [ ]
LabelPatterns.md		| [x]
MarkingHelp.md		| [ ]
MedlineHelp.md		| [x]
arXivHelp.md			| [x]
OpenOfficeIntegration.md	| [ ]
OwnerHelp.md			| [x]
PreviewHelp.md		| [x]
RemoteHelp.md		| [x]
RevisionHistory.md		| [ ]
ScienceDirect.md		| [ ]
SearchHelp.md		| [x]
SpecialFieldsHelp.md	| [x]
INSPIRE.md			| [x]
SpringerHelp.md		| [x]
SQLExport.md			| [ ]
StringEditorHelp.md		| [x]
StringsHelp.md		| [ ]
TimeStampHelp.md		| [x]
XMPHelp.md			| [ ]
----------------------------

**Comment by simonharrer** [comment]
The fetcher fetches data from scraper.bibsonomy.org see https://github.com/JabRef/jabref/blob/34f900a3acd6548e6a3558e745dbbabb5e25e3dd/src/main/java/net/sf/jabref/importer/fetcher/BibsonomyScraper.java

**Comment by mlep** [comment]
How to access this fetcher in the UI?
I could not find it in the web search panel... (JabRef 3.3 and JabRef-3.4dev--snapshot--2016-04-21--master--3f160e8.jar)

**Comment by simonharrer** [comment]
Hm, seems to be unused as part of the SciencedirectFetcher

**Comment by Siedlerchr** [comment]
@mlep  MY PR was merged Yesterday. I included the page names you created. 
https://github.com/JabRef/jabref/pull/1265/commits/b61a7f58974e23d3c46dae0e5c5dd4f271320b8c

As Sciendirect is broken atm I have not included it yet.

**Comment by mlep** [comment]
@Siedlerchr: Thanks; for ScienceDirect, like for BibSonomy, we will wait for further developments.

At the moment, what can be improved?
On my side, I was thinking on reviewing the content of all the help files related to the fetchers. I would like to indicate in these help files that they have been checked. What could be a proper header?
Something like 
> *Up to date for JabRef 3.3*

?

**Comment by Siedlerchr** [comment]
@mlep  Yes, that would be a proper header.
As mentioned before, regarding Fetcchers,  JSTOR can be removed (if not done yet).

If you have need some technicals details checked, must mention me and I'll look into it.

**Comment by mlep** [comment]
@Siedlerchr Indeed, there is no JSTOR.md files in the help now. Just deleted from the above table too.

**Comment by matthiasgeiger** [comment]
I think I would prefer another header:

> ***Caution: Parts of this information are outdated.*** *Please help us to improve this page.*

... of course linked to the contribution guide (#12)
Moreover, we should style this header - red box? Or something like the warning box (here)[https://jekyllrb.com/docs/home/].

**Comment by mlep** [comment]
@matthiasgeiger So, you mean: adding a message when a page is known to be outdated, but not message when it is know to be up-to-date?
I would say: both types of messages, to help us keeping track of the current status.

We also have to think that, within a page, only specific sections can be outdated. Multiple headers will work.

For outdated pages, the code will look like:
```
<div class="note warning">
<h5>Caution: Parts of this information are outdated.</h5>
<p>[Please help us to improve this page.](URL comes here)</p>
</div>
```
...but I have no idea 1) if the class "note warning" is already defined, and, if not, 2) how to define it...

**Comment by matthiasgeiger** [comment]
We are already using bootstrap, so "out-of-box" this should work:
```
<div class="alert alert-danger" role="alert">
  <h5>Caution: Parts of this information are outdated.</h5>
  <p>[Please help us to improve this page.](URL comes here)</p>
</div>
```

See http://getbootstrap.com/components/#alerts or as an alternative: [bootstrap panels](http://getbootstrap.com/components/#panels-alternatives)

One argument against the up-to-date information: This information has to be updated for each release - regardless whether the documented feature has been changed or not.

**Comment by mlep** [comment]
@matthiasgeiger Good point!

**Comment by koppor** [comment]
We can add a flag on the `md` file ( `outdated: true`) and render accordingly.

**Comment by koppor** [comment]
Done at 7c32ae1. Example: http://help.jabref.org/en/ExternalFiles/

**Comment by koppor** [comment]
After https://github.com/JabRef/www.jabref.org/issues/24 is solved, we can also include https://github.com/gjtorikian/jekyll-last-modified-at to (hopefully) show the last modification date of a page.

Side comment: All installed Jekyll plugins on GitHub: https://pages.github.com/versions/

**Comment by mlep** [comment]
**Status update:**

----------------------------
Existing help files		| In HelpFiles.java | Status of content checked (by)
----------------------------	| ------------------------ | ------------------------
ACMPortalHelp.md		| [x]  | [x]  @mlep
ADSHelp.md			| [x]  | [x]  @mlep
arXivHelp.md			| [x] | [x]  @mlep
Autosave.md			| [x] | [ ]
BaseFrameHelp.md		| [ ] | [ ]
**no file**				| Empty argument for FETCHER_BIBSONOMY_SCRAPE | [ ]
BibtexHelp.md			| [ ] | [ ]
CiteSeerHelp.md		| [x] | [x]  @mlep
CommandLine.md		| Empty argument for COMMAND_LINE | [ ]
ContentSelectorHelp.md	| [x] | [ ]
cpl-v10.md			| [ ] | [ ]
CustomEntriesHelp.md	| [ ] | [ ]
CustomExports.md		| [x] | [ ]
CustomImports.md		| [x] | [ ]
DatabaseProperties.md	| [ ] | [ ]
DiVAtoBibTeXHelp.md	| [x] | [x]  @mlep
DBLPHelp.md			| [x] | [x]  @mlep
DOAJHelp.md			| [x] | [x]  @mlep
DOItoBibTeXHelp.md	| [x] | [ ]
EndNoteFilters.md		| [ ] | [ ]
EntryEditorHelp.md		| [x] | [ ]
ExternalFiles.md		| [x] | [x] @koppor 
FileLinks.md			| [ ] | [ ]
GeneralFields.md		| [x] | [ ]
GoogleScholarHelp.md	| [x] | [x]  @mlep
GroupsHelp.md		| [x] | [ ]
GVKHelp.md			| [x] | [x]  @mlep
HelpHelp.md			| [ ] | [ ]
IEEEXploreHelp.md		| [x] | [x]  @mlep
ImportInspectionDialog.md	| [x] | [ ]
index.md				| Empty argument for CONTENTS | [x] @mlep
ISBNtoBibTeXHelp.md	| [x] | [ ]
JabRefHelp.md		| [ ] | [ ]
JournalAbbreviations.md	| [x] | [ ]
LabelPatterns.md		| [x] | [ ]
MarkingHelp.md		| [ ] | [ ]
MedlineHelp.md		| [x] | [x]  @mlep
OpenOfficeIntegration.md	| [ ] | [ ]
OwnerHelp.md			| [x] | [ ]
PreviewHelp.md		| [x] | [ ]
RemoteHelp.md		| [x] | [ ]
RevisionHistory.md		| [ ] | [x] @koppor 
ScienceDirect.md		| [ ] | [ ]
SearchHelp.md		| [x] | [ ]
SpecialFieldsHelp.md	| [x] | [ ]
INSPIRE.md			| [x] | [x]  @mlep
SpringerHelp.md		| [x] | [ ]
SQLExport.md			| [ ] | [ ]
StringEditorHelp.md		| [x] | [ ]
StringsHelp.md		| [ ] | [ ]
TimeStampHelp.md		| [x] | [ ]
XMPHelp.md			| [ ] | [ ]
----------------------------


----------------------------
Missing help files		|
----------------------------	|
BibLaTeX.md		|
----------------------------

**Comment by matthiasgeiger** [comment]
(checked some Help pages - and marked some of them as outdated)
Will continue in the next days...

**Comment by mlep** [comment]
I have just updated the table above.

For help files, we need to finish to define, for each file, if it is up-do-date or outdated.
This has been done for most of the files, except the followings:

- [BibtexKeyPatterns.md ](https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/BibtexKeyPatterns.md )
- [cpl-v10.md](https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/cpl-v10.md). Is it the proper license? (considering there was a change in the license for JabRef code)
- [CustomExports.md](CustomExports.md)
- [CustomImports.md](CustomImports.md)
- [JournalAbbreviations.md](JournalAbbreviations.md)
- [OpenOfficeIntegration.md](OpenOfficeIntegration.md)
- [PreviewHelp.md](PreviewHelp.md)
- [RemoteHelp.md](RemoteHelp.md)
- [XMPHelp.md](XMPHelp.md)

I do not use these features enough to judge...

Next steps will be:
1) set priorities for updating the pages
   - based on consultation statistics?

2) inform translators (and other users) when a new page is considered up-to-date, and so worth translating
  - how?

**Comment by Siedlerchr** [comment]
License must be now MIT: https://opensource.org/licenses/MIT
I think regarding OpenOffice Integration @oscargus  can maybe check it, as he worked on the code more or less recently...

**Comment by koppor** [comment]
Due to a) stopping supporting non-English language (for now) and b) having "outdated" headers at each page, one can click through <https://docs.jabref.org/> and (hopefully 😄 ) easily see, where to start.

Refs https://github.com/JabRef/help.jabref.org/issues/178#issuecomment-553623075
