### ISSUE TITLE
Help about translating help

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#113]
I am planning to create a file about how to translate the help files. Steps described below.

**Issue**: how to avoid to have a quasi-duplicate of https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md ?
Suggestion: the automate.py script should duplicate the file en/TranslatingHelp.md into CONTRIBUTING.md

1) Create a file https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/TranslatingHelp.md
2) get and update information from 
https://github.com/JabRef/jabref/wiki/Translating-JabRef-Interface
and
https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md
3) Mention the specific status of index.md (It is generated by a script)
4) Status of translations: Mention script: https://github.com/JabRef/help.jabref.org/pull/77
5) Explain how to translate section headers (files like https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/localization_en.json)

**Comment by koppor** [comment]
I think, everything is covered in https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md#note-when-translating-pages

The explanation of the generation of index.md can be improved, though.

**Comment by koppor** [comment]
I think, it should be enough to link https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md from whereever you think it's reasonable.

In that file, I also added step 10, which links https://github.com/JabRef/help.jabref.org/tree/gh-pages/_scripts.
