### ISSUE TITLE
Support fetch from Medline via https

### ISSUE THREAD

**Issue by chenliangomc** [JabRef/help.jabref.org#130]
As 2016-11-02 1539 EDT fetching article information from Medline fails with blank message dialog pops up then another message dialog with "no references found".

JabRef version: 3.6 release

The test target: https://www.ncbi.nlm.nih.gov/pubmed/15325740/

The test was performed during NCBI secure website test, see also https://www.ncbi.nlm.nih.gov/home/bulletins/https-tests.shtml

**Comment by chenliangomc** [comment]
With netstat, I can confirm that version 3.6 still connects to port 80 (http), not 443 (https).

**Comment by Siedlerchr** [comment]
Thanks for your information! I will check if that is working in the current development version, because there has been some changes to Medline.

**Comment by matthiasgeiger** [comment]
Issue will be tracked in main repository https://github.com/JabRef/jabref/issues/2228.

**Comment by Siedlerchr** [comment]
@chenliangomc  The issue is now fixed in the latest dev build. Please try again with the current master from  https://builds.jabref.org/master/

Older versions of JabRef will no longer work.
