### ISSUE TITLE
Index: new section not displayed

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#132]
The page https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/TranslatingGUI.md introduced a section "Contributing".
While it was merged 25 days ago, the index does not list this page nor the section "Contributing".

Is it a bug, or does the update of the index needs to be triggered manually?

**Comment by koppor** [comment]
The update currently needs to be triggered manually. The scripts `automate.py` currently doesn't run on my side, I contacted @bartsch-dev

**Comment by bartsch-dev** [comment]
I fixed this and some others in the linked PR.
