### ISSUE TITLE
DOI-, Diva- and ISBN-to-BibTeX moved to New entry...

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#137]
Since JabRef 3.7, DOI-, Diva- and ISBN-to-BibTeX  are not under WebSearch anymore.
They are now in BibTeX --> New entry...

Help files should be updated accordingly.

**Comment by matthiasgeiger** [comment]
Potentially useful screenshot:
https://cdn-standard.discourse.org/uploads/jabref/optimized/1X/8c5b0ec7bf8136a38fc2962c6cb37946c16c3b45_1_381x500.png

(used here http://discourse.jabref.org/t/wheres-the-plugin-menu/358/3)

**Comment by koppor** [comment]
I updated

 - https://help.jabref.org/en/DiVAtoBibTeX
 - http://help.jabref.org/en/DOItoBibTeX
 - http://help.jabref.org/en/ISBNtoBibTeX

And the index https://help.jabref.org/en/

I hope, this is enough, even though the screenshots could be optimized.

**Comment by matthiasgeiger** [comment]
I have fixed the header information (3.7 instead of 3.6) and updated the screenshots.

**Comment by koppor** [comment]
The TOC is not very flexible. We would have to adapt [automate.py](https://github.com/JabRef/help.jabref.org/blob/gh-pages/_scripts/automate.py) accordingly.

**Comment by matthiasgeiger** [comment]
Okay... Then we should create additional pages for the Medline/ADS "create by id" ability (and potentially cross link from the general WebFetcher pages https://help.jabref.org/en/Medline and https://help.jabref.org/en/ADS
