### ISSUE TITLE
To write: help describing Document the feature "Merge with DOI information"

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#15]
The current version of JabRef (3.3) does not include a help about  the feature "Merge with DOI information".
A help file should be written. It should include the recent improvement (highlighting of differences in merge entries). See https://github.com/JabRef/jabref/pull/1022.

To be done for the next version of JabRef (3.4)

On-hold for now.

**Comment by koppor** [comment]
Stub available at https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/MergeEntries.md

**Comment by mlep** [comment]
In fact, "Merge entries" is different from "Merge with DOI information"
