### ISSUE TITLE
Hangs forever when saving file with a key with {\"u} in it

### ISSUE THREAD

**Issue by karyon** [JabRef/help.jabref.org#153]
loading this file
```
@ARTICLE{Biguen.etal-1991,
  pdf = {Big{\"u}n - some title.pdf}
}
```

jabref will ask something about updating pdf links. when clicking yes, and then saving the file, jabref just says "saving database..." forever and never finishes. when closing jabref, it says something like "waiting for saving operation to finish".

**Comment by koppor** [comment]
Could you please open the issue at https://github.com/JabRef/jabref/issues? This allows us to track the issues of JabRef as a whole. This repo is for the web site of JabRef. Sorry for any confusion caused.

**Comment by karyon** [comment]
oops sorry, my bad.

https://github.com/JabRef/jabref/issues/2439
