### ISSUE TITLE
Explain directory lookup

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#160]
See https://github.com/JabRef/jabref/pull/459#issuecomment-161817966

**Comment by Siedlerchr** [comment]
Use bib file dir as main directory ignores all other dirs. That changed
with 3.8


Am 16.04.2017 8:33 vorm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by koppor** [comment]
Done in https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/FileLinks.md#directories-for-files
