### ISSUE TITLE
Make keyboard shortcuts a bit less prominent

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/help.jabref.org#161]
Currently, keyboard shortcuts have a black background that make them really standout from the rest of the text. For example, compare 
http://help.jabref.org/en/EntryEditor
to the github version 
https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/EntryEditor.md,
which is more readable.

**Comment by sameshl** [comment]
@tobiasdiez I would love to work on this. I researched a bit on how it could be done but did not get any solution. Can you help me on what I could do here?

Thanks!

**Comment by koppor** [comment]
With the transition to gitbooks, the whole html marking `<kbd>...</kbd>` is removed:

![grafik](https://user-images.githubusercontent.com/1366654/68648035-ac3c9d00-051f-11ea-9827-66ac9cba4998.png)

Since we decided to move to gitbook (refs #178), we cannot do anything here.
