### ISSUE TITLE
extremely  slow when double click on entry to open entry edit panel [version 4.0, mac] 

### ISSUE THREAD

**Issue by BioinfoTongLI** [JabRef/help.jabref.org#169]
Just a feed back. 
last version of 3.xx worked fine on my mac.
But with 4.0, opening the entry edit panel can take up to 1 min.
During this, the interface is freezed.

I'm using high sierra
java 1.8

**Comment by BioinfoTongLI** [comment]
Oops, maybe i should post this in jabref repo? Sry i didn't pay attention on repo name.

**Comment by tobiasdiez** [comment]
Yes please post it in the main repository. Also note that we recently had similar reports and a solution is described in the last question in the [FAQ](https://github.com/JabRef/help.jabref.org/blob/91a5ba29b2b2e688c2132b8196fe9d3c2685218a/en/FAQosx.md#q-jabref-slowhangs-on-macos-sierra). Hopefully this helps you, too.
