### ISSUE TITLE
Automatic update of translation status

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#171]
Using the new version of SyncLang.py (see PR https://github.com/JabRef/jabref/pull/3184), could it be possible to automatically generate the translation status with each push to master, and update the page https://help.jabref.org/en/TranslatingGUI ?

Note: this issue was mentioned in https://github.com/JabRef/jabref/pull/3184 , but since it is now merged, I guess a new issue is needed to keep track of it.

**Comment by LinusDietz** [comment]
Actually, I kept issue https://github.com/JabRef/jabref/issues/3181 intentionally open, but then I'll close it.

This automatic update should not be a big deal, it just takes some time fiddling around with the continuous integration.

**Comment by Siedlerchr** [comment]
I think as the translation status is now directly visible in crowdin, we can close this issue
