### ISSUE TITLE
Add help for the IACR eprint fetcher

### ISSUE THREAD

**Issue by derTimme** [JabRef/help.jabref.org#176]
I'm currently working on a new web fetcher for [IACR eprints](https://eprint.iacr.org/), see JabRef/jabref#3473 in the code repository.
The help will probably look like the one for the DOI ID based fetcher (it currently only supports ID based fetching).

**Comment by derTimme** [comment]
The fetcher is now mostly finished - one can fetch entries by an ID like `2017/1118` or `1996/002`.
The ID always has to consist of a four-digit year, followed by a forward slash, followed by a number with at least three digits (including leading zeroes if necessary). Four digits are only allowed for numbers >= 1000.

Whitespace and characters around this are simply ignored (this allows to copy the ID from somewhere without having to be extra cautious about copying too much). But this probably doesn't need to be part of the help page, as digits and forward slashes aren't allowed (internally, the fetcher just throws away anything but digits and forward slashes).

Some of the papers in the IACR eprint archive have been withdrawn (e.g. [`1998/016`](https://eprint.iacr.org/1998/016)). When the user tries to fetch an entry for a withdrawn paper, the fetcher will exit with a corresponding error message (the entry can still be added "manually". Throwing an error is the only way I could think of to reliably warn the user - which will be even more important if we add a "search by title" or something similar in the future).

**Comment by Siedlerchr** [comment]
I am just asking, it's been a while since you contributed the ICAR fetcher.  It would be really nice, if you could add the missing help as well! Thanks!
