### ISSUE TITLE
Add FAQ for missing dois.

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#183]
https://www.xing.com/events/be-aware-graphs-are-everywhere-1913412

Because it is not listed at crossref.org which is used by us: search.crossref.org/?q=10.3233%2FSW-2012-0062

Refs https://github.com/koppor/jabref/issues/322

**Comment by michizhou** [comment]
I'd be glad to work on this one! Please feel free to let me know what I need to do. Feel free to also provide any supplemental information that could guide me.

**Comment by koppor** [comment]
The linked issue should contain enough information. May I asked whether you used the DOI fetching functionality of JabRef? See http://help.jabref.org/en/DOItoBibTeX for a documentation.
