### ISSUE TITLE
Document -importBibtex command line argument

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/help.jabref.org#184]
In https://github.com/JabRef/jabref/pull/3246 a new command line argument `-importBibtex` was added which works similar to the import of files option but directly accepts bibtex code as argument.

**Comment by michizhou** [comment]
I can take this one. Just fill me in on the specifics of what I need to do. If there is any sort of supplemental information that I might need, just let me know.

**Comment by koppor** [comment]
@michizhou Please start JabRef and dive into the feature. Play around with bibtex files.
