### ISSUE TITLE
Remove "Help" suffix

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#19]
Most help files have the suffix `Help`, while some do not. See for instance https://github.com/JabRef/help.jabref.org/tree/gh-pages/fr

I would propose to remove the Help suffix completely at all help files.

**Comment by koppor** [comment]
Do not forget to add redirect: https://help.github.com/articles/redirects-on-github-pages/ and adapt  net.sf.jabref.logic.help.HelpFile

**Comment by matthiasgeiger** [comment]
Somehow related... Can this redirect stuff also be used to "redirect" from a unexisting localized Help page to the existing english one? (See #41)

**Comment by bartsch-dev** [comment]
I'll work on the redirect issue.

**Comment by bartsch-dev** [comment]
If we generate the index (#74) we won't need the redirect pages, as we could link from the index directly to the English version if the page doesn't exist in the language.
But if someone translates a new page he would need to run the script (which needs python) or someone immediately after the merge has to.

**Comment by koppor** [comment]
We need the redirect for the old JabRef versions running at the users

Example:

>     FETCHER_ISBN_TO_BIBTEX("ISBNtoBibTeXHelp"),

**Comment by koppor** [comment]
Fixed by #77
