### ISSUE TITLE
Advertise unpaywall

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#190]
https://unpaywall.org/

See http://discourse.jabref.org/t/unpaywall-integration-for-attachments/1243/2?u=koppor

**Comment by michizhou** [comment]
I'd be glad to work on this one! Please feel free to let me know what I need to do in terms of how to advertise and where to put it. If there is supplemental information that could help me, let me know.

**Comment by koppor** [comment]
Please look at the JabRef code and reverse engineer the feature. Then write a documentation on it.
