### ISSUE TITLE
Document - New preference option to add files in Entry Editor

### ISSUE THREAD

**Issue by shahamish150294** [JabRef/help.jabref.org#194]
Under https://help.jabref.org/en/EntryEditor, add documentation to explain in detail the three different behaviors when file(s) are dragged and dropped in the entry editor. These behaviors can be set by the user through Preferences.
Issue: https://github.com/JabRef/jabref/issues/4356
PR: https://github.com/JabRef/jabref/pull/4408

**Comment by michizhou** [comment]
If it's no trouble, I'd love to take on this issue. If there is other supplemental information not found in the issue, PR, or other links on this page that could help me, just let me know!

**Comment by shahamish150294** [comment]
Hi @michizhou feel free to work on this issue. All the related and helpful links to the task are mentioned in the description. Thank you!
