### ISSUE TITLE
Creating a FAQ

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#2]
What about creating a FAQ?
We could develop it progressively, based on the questions asked on the mailing list.

**Comment by oscargus** [comment]
Sounds like an excellent idea!

I'm also thinking about how we should get people to report (search for previous) issues at GitHub rather than on the mailing list...

**Comment by koppor** [comment]
I know that our old FAQ at http://jabref.sourceforge.net/faq.php is ugly, but it contains many information and I tried to keep it updated time by time. But it was too much work for me. I would be happy if you took over. :sunny: 

I'm trying to port it to github ASAP. Refs https://github.com/JabRef/jabref/issues/111.

**Comment by mlep** [comment]
I can take over, but I will need help for some sections (developers, macOSX, etc.)

**Comment by simonharrer** [comment]
Sounds great. For Mac OS X, @chochreiner may be of help as he did the major Mac OS X improvements targeted for JabRef 3.3

**Comment by koppor** [comment]
The newly designed FAQ is available at http://www.jabref.org/faq/. I hope, that is a good start.

**Comment by mlep** [comment]
Thanks.
However, the "edit" buttons located on the right of the section titles give a 404 error message.
The colors are kind of hurting my eyes, especially the green and the blue.

**Comment by koppor** [comment]
Colors: Feel free to change at the header of https://github.com/JabRef/www.jabref.org/blob/gh-pages/_faq/10_general.md and the other files

```
bg: turquoise
color: white
```

The colors themselves can be written as `#RRGGBB` or reusing the globally definitions at https://github.com/JabRef/www.jabref.org/blob/gh-pages/_config.yml.

Regarding the link: It used to work yesterday, I'll have a look.

**Comment by koppor** [comment]
Link fixed in https://github.com/JabRef/www.jabref.org/commit/0702be5f5e8488093ff3b4d3c6ebe562df05bc3c. Thanks to https://github.com/jekyll/jekyll/issues/2897#issuecomment-55147204. If there is more concerning www.jabref.org, please file an issue at https://github.com/JabRef/www.jabref.org/issues.

**Comment by mlep** [comment]
OK, thanks.

**Comment by mlep** [comment]
I could install Jekyll. Looks convenient!
