### ISSUE TITLE
Update suggestion /en/Installation.md: Ubuntu 18.04 openjfx

### ISSUE THREAD

**Issue by Druidefix** [JabRef/help.jabref.org#204]
For my Ubuntu 18.04 installation I got three updates today that broke my JabRef 4.3.1 support.

From the `/var/log/apt/term.log`

```
Unpacking libopenjfx-java (11.0.2+1-1~18.04.2) over (8u161-b12-1ubuntu2)
Unpacking libopenjfx-jni (11.0.2+1-1~18.04.2) over (8u161-b12-1ubuntu2)
Unpacking libopenjfx-java (11.0.2+1-1~18.04.2) over (8u161-b12-1ubuntu2)
```

From [this thread](http://discourse.jabref.org/t/1476) I think the version is now too new and belongs to Java Version 11 which is currently not supported.

Hence, I removed `openjfx` with `apt purge openjfx` and removed the other two packages with `apt autoremove` such that I can install the previous versions

`apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2`

Then I marked those packages to be not upgraded

`apt-mark hold openjfx libopenjfx-jni libopenjfx-java`

Perhaps this information could help other Ubuntu 18.04 users who got the same package updates today and are now without JabRef 4.3.1 support as it only was showing

`Error: Could not find or load main class org.jabref.JabRefMain`

before. So, is this worth mentioning in `en/Installation.md`?

**Comment by Siedlerchr** [comment]
Yes, you are right. The new version is Java 11, under which JabRef does not yet work.
JabRef still requires Java 8.

For the dev version there is also a snap package available

**Comment by ygoramaral** [comment]
This workaround worked for me on Linux Mint 19.1 Tessa (Ubuntu 18.04 based). Thanks!

**Comment by csap9871** [comment]
Thanks for that workaround! The only useful solution I could find for the same problem.
(also on Linux Mint 19.1 Tessa)

**Comment by tobiasdiez** [comment]
@Druidefix @ygoramaral @csap9871 As many users appear to have this issue, could you please add these steps to the installation instructions https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/Installation.md. Thanks!

**Comment by Druidefix** [comment]
@tobiasdiez: I created my first pull request here in GitHub. Hopefully I did not forget something / messed something up, as I am used to GitLab.

**Comment by tobiasdiez** [comment]
Perfect. Thanks a lot!

**Comment by sdaau** [comment]
Sorry for reopening, but this is not quite complete info; at start, on Ubuntu 18.04, I had:

```
$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

$ sudo update-alternatives --config java
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-11-openjdk-amd64/bin/java
Nothing to configure.
```

After I failed to run with `java -jar JabRef-4.3.1.jar`, I found the instructions on http://help.jabref.org/en/Installation, and did:

```
sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
sudo apt-mark hold openjfx libopenjfx-jni libopenjfx-java
```
... but `java -jar JabRef-4.3.1.jar` still failed, since it still calls java 11.

But, at this point we can see:

```
$ sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: ^C
```
... so, we can run java 8 just with using absolute path, which works:

```
$ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar JabRef-4.3.1.jar 
21:19:09.127 [AWT-EventQueue-1] INFO  org.jabref.migrations.PreferencesMigrations - Migrating old custom entry types.
21:19:09.243 [AWT-EventQueue-1] WARN  org.jabref.JabRefGUI - There seems to be problems with GTK Look&Feel. Using Nimbus L&F instead. Change to another L&F with caution.
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
^C
```

**Comment by Siedlerchr** [comment]
But if you switch the Java update alternative to Java 8 it should work then
