### ISSUE TITLE
Push to external application

### ISSUE THREAD

**Issue by calixtus** [JabRef/help.jabref.org#207]
There is no documentation about configuring push-to-external-application nor the actual use by clicking in the toolbar, in the menu and also not on selecting a different external application to push to. See [JabRef/jabref#4991](https://github.com/JabRef/jabref/pull/4991)

**Comment by michizhou** [comment]
If it's no trouble, I'd love to take on this issue. If you could kindly provide any sort of supplemental information or background to help me get started, I'd really appreciate it!

**Comment by koppor** [comment]
@michizhou You should read along the linked issue and try to get a picture. I did not find any information on your background. Did you ever use JabRef and a LaTeX editor? If not, please try to start with that. Then you might get a understanding what this feature is about.
