### ISSUE TITLE
Add documentation for Allow negation (`!`, NOT operator) in \\begin{...} conditionals 

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#209]
Add documentation for https://github.com/JabRef/jabref/pull/5138

**Comment by domwass** [comment]
Vielen Dank für Ihre Nachricht.
Ich bin erst wieder ab dem 26. August 2019 erreichbar. Bitte beachten Sie, dass Ihre E-Mails nicht weitergeleitet werden. Ich werde die eingegangenen E-Mails nach meiner Rückkehr bearbeiten und bitte daher um etwas Geduld.
Mit besten Grüßen 
Dominik Waßenhoven.-

Thank you for your message.
I am currently out of office, but will be available again from 26 August 2019. Please note that your message will not be forwarded. I will process the inbox after my return and would kindly ask you to be forbearing. 
With best wishes 
Dominik Waßenhoven.-

**Comment by koppor** [comment]
Fixed in https://github.com/JabRef/help.jabref.org/pull/212
