### ISSUE TITLE
Port scripts to Python3

### ISSUE THREAD

**Issue by ju-sh** [JabRef/help.jabref.org#226]
Can we port the Python2 scripts used in this repo to Python3.

Since Python2 support will soon end. Python3.7 is the latest, maybe we can use that?

Changes would be needed in the readme about installing Python3 as well if porting is done.

**Comment by Siedlerchr** [comment]
Sounds like a good idea.! Go ahead

**Comment by ju-sh** [comment]
Okay. Working on it.

**Comment by ju-sh** [comment]
I think I'll have to spend a long time doing this on my own. If anybody would like to take over, it would be cool.

**Comment by koppor** [comment]
Let's focus on more important things!
