### ISSUE TITLE
Convert old wiki pages to help pages

### ISSUE THREAD

**Issue by simonharrer** [JabRef/help.jabref.org#32]
https://sourceforge.net/p/jabref/wiki/Main_Page/

**Comment by mlep** [comment]
Regular expressions are being moved to the help.
Which others need to be moved?

The potential ones are:

- [Create a custom PDF files list filter]()
- [Developing_and_extending_JabRef]()
- [Protecting Formatting](https://sourceforge.net/p/jabref/wiki/ProtectingFormating/)
- [Summer_of_Code](https://sourceforge.net/p/jabref/wiki/Summer_of_Code/)
- [Getting_started_with_JabRef_plugin_development](https://sourceforge.net/p/jabref/wiki/Getting_started_with_JabRef_plugin_development/)
- [HOWTO_for_JabRef's_switch_from_Subversion_to_Git](https://sourceforge.net/p/jabref/wiki/HOWTO_for_JabRef%27s_switch_from_Subversion_to_Git/)
- [Developing_JabRef_in_Netbeans](https://sourceforge.net/p/jabref/wiki/Developing_JabRef_in_Netbeans/)

**Comment by koppor** [comment]
Done. Thanks at @mlep for converting most of the pages.
