### ISSUE TITLE
English version of page if there is no translation

### ISSUE THREAD

**Issue by oscargus** [JabRef/help.jabref.org#41]
When running the Swedish translation, JabRef looks for Swedish help pages. It would be great if a link pointing to the English (or available languages) showed up instead of the 404.

**Comment by koppor** [comment]
Please do not copy. This increased redudancy.

We can add redirects as mentioned at https://github.com/JabRef/help.jabref.org/issues/19#issuecomment-242304190

**Comment by koppor** [comment]
Fixed by #77
