### ISSUE TITLE
Duplicate LabelPatterns pages to BibtexKeyPatterns

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/help.jabref.org#45]
At least until 3.6 is released pages should be available under both names.

(See https://github.com/JabRef/jabref/pull/1704)

**Comment by koppor** [comment]
I would just rename the page and create a new page LabelPatterns stating that these are called "BibtexKeyPatterns" in JabRef 3.6 onwards. Reason: We should keep our help updated for the current version of JabRef. Pointers for old users are OK, but maintaining different versions of the help for different versions of JabRef is hell.

**Comment by matthiasgeiger** [comment]
Yes, that was my plan for the time after 3.6 is released. But we can also rename at once and the few Users accessing the page before 3.6 will have to do an additional click.

Am 11.08.2016 2:13 vorm. schrieb Oliver Kopp <notifications@github.com>:

I would just rename the page and create a new page LabelPatterns stating that these are called "BibtexKeyPatterns" in JabRef 3.6 onwards. Reason: We should keep our help updated for the current version of JabRef. Pointers for old users are OK, but maintaining different versions of the help for different versions of JabRef is hell.
