### ISSUE TITLE
MedlineRIS.md : table not displayed as table

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#54]
While the table is correctly shown at
https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/MedlineRIS.md
it is not at
http://help.jabref.org/en/MedlineRIS

Could not find a syntax error...

Firefox 48 & Chromium 52

**Comment by koppor** [comment]
GitHub and Jekyll use different renderers. @zellerdev tries to take care

**Comment by mlep** [comment]
Solved  @koppor 
https://github.com/JabRef/help.jabref.org/commit/bae379ab50e4c44f6b6be8ebead0f1921d650725
and
https://github.com/JabRef/help.jabref.org/commit/ac0b0f60462d3e2b15e5bacd60592516960f6ccf
