### ISSUE TITLE
Database properties: general file directory vs user-specific file directory

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#55]
In http://help.jabref.org/en/DatabaseProperties , section "Override default file directories":
what is the difference between "general file directory" and "user-specific file directory"?

**Comment by koppor** [comment]
General File Directory: Directory used for files. Can be overridden at the user-specific file directory. JabRef stores for the name of the current system a file directory. This assumes that each user of the database has a different system name. When the database is shared between different users, each user can have different locations of the files. One cannot see the file directory setting for the other user, but it is stored inside the bib file. E.g., when using `laptop`, the entry in the `bib` file is `@Comment{jabref-meta: fileDirectory-jabref-laptop:\\somedir;}`

**Comment by mlep** [comment]
Thanks for the explanation!
Added ( https://github.com/JabRef/help.jabref.org/commit/a16c6cb437e3218bffb1dc490008a64241d8c02c )
