### ISSUE TITLE
http://help.jabref.org/en/HelpHelp/ does not make any sense anymore

### ISSUE THREAD

**Issue by simonharrer** [JabRef/help.jabref.org#6]
Can be removed, I think.

**Comment by koppor** [comment]
Because we moved to online help files (see https://github.com/JabRef/jabref/pull/724), we can surely remove that in all languages.That reminds me to add a custom 404 page.

**Comment by mlep** [comment]
HelpHelp.md removed (see commit https://github.com/JabRef/help.jabref.org/commit/26d8cd398d76585bf83c5fa9f711f4e100e7d534)
