### ISSUE TITLE
Sync other language index files when new file in en is added

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/help.jabref.org#74]
It would be cool to have script or whatever to automatically add the new untranslated page links to the other language index files.
This should be relative simple by just checking if the pagename is already present in the other language files. That would also work for non Latin-Languages like Japanese. 

Currently the help pages for each index have to be adapted manually

**Comment by koppor** [comment]
@bartsch-dev could you take care? 😇

**Comment by bartsch-dev** [comment]
I'll look into it.

**Comment by bartsch-dev** [comment]
The easiest way would be to define a category in the front matter of each help file, that way (and with the title) I can easily generate the index file of each language

**Comment by Siedlerchr** [comment]
Category is simple, I think you can just define a custom variable: https://jekyllrb.com/docs/frontmatter/#custom-variables
But we have to be aware that we do not overwrite the already translated links in the files.
Regarding the script, Python would be okay. We could adapt the CI Build script to automatically execute it.

**Comment by koppor** [comment]
Fixed by #77
