### ISSUE TITLE
404 and other error pages: how to find them?

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#76]
Among the various pages, some of them probably contain wrong URL.
Is there a mechanism to have the list of such URL (and the pages which contain them)?
(I guess this question is also valid for www.jabref.org)

**Comment by koppor** [comment]
You mean an internally wrong linking?

This can be done using html-proof, but this tool currently does not work - see https://github.com/JabRef/www.jabref.org/issues/17

**Comment by mlep** [comment]
I meant internal and external.

**Comment by koppor** [comment]
On bash:

```bash
$ find . -name \*.md -exec markdown-link-check -qq {} \; > bad-links.txt
```

Link to the tool: https://github.com/tcort/markdown-link-check

I executed the script and fixed all links on docs.jabref.org. - Added the howto to https://github.com/JabRef/help.jabref.org/blob/master/README.md#how-to-find-broken-links.

What we cannot check (with the current man power) is analyzing incoming external links and redirecting to the correct help page. I hope, it is OK for users to use the search functionality. - In case, it is too annoying, I can build redirection pages on help.jabref.org. However, this will take a few ours and I want to focus on other things 🔥 .
