### ISSUE TITLE
Title in the frontmatter of fr/Autosave is wrong

### ISSUE THREAD

**Issue by bartsch-dev** [JabRef/help.jabref.org#79]
The title of the file `fr/Autosave` is very long (and the same as the first line after the frontmatter).
It should be fairly simple but as my french is a bit rusty I would let do it someone else.

Background: I need the correct title to generate the index files (#77)

**Comment by Siedlerchr** [comment]
@mlep  Could you please help here?

**Comment by mlep** [comment]
Done in PR https://github.com/JabRef/help.jabref.org/pull/81

**Comment by Siedlerchr** [comment]
@bartsch-dev  Just merged the changes in.
