### ISSUE TITLE
Document save actions

### ISSUE THREAD

**Issue by lenhard** [JabRef/help.jabref.org#8]
Save actions are introduced as a new feature. This should be documented.

The feature itself is not that complex, but the variety of formatters that are available are not documented. Hence, we need a short documentation for each formatter.

**Comment by lenhard** [comment]
The documentation should go to http://help.jabref.org/en/CustomExports

However, there is a lot of outdated text there and none of the recent formatters are documented.

**Comment by Siedlerchr** [comment]
We have a help file for save actions, therefore I close this issue
