### ISSUE TITLE
No help page: create an empty file or an issue?

### ISSUE THREAD

**Issue by mlep** [JabRef/help.jabref.org#88]
Several (numerous?) features do not have an help page yet (e.g. Cleanup entries, Manage protected terms). How to foster their writing?
1) create an issue signaling the missing help page and calling for a contribution.
or
2) create a help file with a message stating that a contribution is welcome.

I believe option 2 is preferable because:
- it will give more chance to find contributors. 
- by counting the number of connections to the help page, we will know which help pages to write in priority (related to https://github.com/JabRef/help.jabref.org/issues/11)

Any thought?

**Comment by koppor** [comment]
Option 2. Just go ahead for creating. The I will create the index file and the other language files with the [Python script](https://github.com/JabRef/help.jabref.org/tree/gh-pages/_scripts) to generate the index file and the  other files in the other languages.
